# Generated by Django 2.2.4 on 2019-11-14 23:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_a',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='eithers/images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_b',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='eithers/images'),
        ),
    ]
